### ISSUE TITLE
Genome-wide analysis using iSAFE

### ISSUE THREAD

**Issue by andreyurch** [alek0991/iSAFE#6]
Dear developers,

Thank you very much for very interesting methodology proposed! After reading the article in Nat Met I would like to clarify the following question: the method is mainly described as an additional tool to identify causative variants in a window with signature of selection already identified by another method. Is it possible to use iSAFE score in overlapping (or non overlapping) windows across whole genome as a primary method to identify regions under selection based on the empirical iSAFE distribution and then find putative causative variants? If not - what is the main problem with such an approach?

Best regards,
Andrey

**Comment by alek0991** [comment]
Dear Andrey, 

I try to answer your query in two parts:
#### 1- iSAFE is primarily designed to pinpoint the favored mutation. Can it also be used as a test of selection to detect regions under selection? 
During the past few decades many test of selection have been developed to identify the region under selection and LD structure around the favored mutation makes it possible to detect these regions. However, the LD structure makes it hard to pinpoint the favored mutation. We didn't try to devise a better test of selection and indeed iSAFE is designed with the goal of pinpointing the favored mutation in positive selective sweep. However, iSAFE is also very powerful to detect the region under selection (see the following paragraph and attached figure).

In  [Supplementary Figure 29](https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-018-03100-7/MediaObjects/41467_2018_3100_MOESM1_ESM.pdf) of [Sugden et al., 2018](https://www.nature.com/articles/s41467-018-03100-7) they compared iSAFE and a modified version of SWIF(r) by incorporating iSAFE as a component statistic (called SWIF(r)+iSAFE). Attached figure (that combines information in Supplementary Figure 29 and Figure 1a of Sugden et al., 2018) shows that iSAFE outperforms SWIF(r) and by incorporating iSAFE as a component statistic in SWIF(r) the overall performance of SWIF(r) improves and exceeds that of iSAFE, because SWIF(r) can leverage the joint distributions of iSAFE with other component statistics.

<figure>
  <img src="https://user-images.githubusercontent.com/11303721/108679712-f5b5bf00-74ba-11eb-9126-8911177ccca3.png"  width="500">
  <figcaption><em>Combined information from Supplementary Figure 29 and Figure 1a of Sugden et al., 2018.</em></figcaption>
</figure>

\
\
This analysis shows the power of iSAFE to detect regions under selection. 

#### 2- How can we do genome-wide analysis of selection using iSAFE?
I would recommend an overlapping sliding window of size _3s_ (e.g., 3Mbp for s=1Mbp) with step size _s_. Break each window into three equal chunks of size _s_ and keep the values of iSAFE for the middle chunk and discard the values for the shoulder chunks. Therefore, in each window you are calculating the iSAFE scores for the middle chunk of size _s_.
\
\
Hope you find this useful in your research and please let me know if you have any question or I can be of any help. 
Best,
Ali

**Comment by andreyurch** [comment]
Dear Ali, 

Thank you for the very informative answer. I will try the abovementioned methodologies. Interestingly, I missed the paper of Sugden et al 2018 among the works which cite your work (https://scholar.google.com/scholar?start=0&hl=ru&as_sdt=2005&sciodt=0,5&cites=6084582749494780743&scipsc=) because it cites your preprint but not the final version. 

Best regards,
Andrey
