### ISSUE TITLE
Multiple iSAFE peaks

### ISSUE THREAD

**Issue by psytky03** [alek0991/iSAFE#9]
Dear Ali,
May I ask how should I interpret the results when a locus contains multiple peaks? I expected to see a signal close to the iHS peak (there was only 1 iHS peak), but several iSAFE peaks were seen in the flanking upstream/downstream regions, does this indicates false positives of iHS? 

Thanks
Xiaoxi

**Comment by alek0991** [comment]
Dear Xiaoxi, 
The short answer is that iSAFE has higher resolution and multiple peaks can be due to multiple selective sweeps.  

 iHS is a test to detect a region under selection (not pinpointing the favored mutation) and it does a great job to detect ongoing selective sweeps. However, iSAFE is designed to tackle this issue and pinpoint the favored mutation. Although, iSAFE is also shown to be very powerful to be used as a test of selection (i.e. find the region under selection). Please also check https://github.com/alek0991/iSAFE/issues/6#issuecomment-783219198 which is relevant to this topic. 

Please let me know if you have any other questions.
Best,
Ali

**Comment by psytky03** [comment]
Hi, Ali,
Thanks for the kind explanations. Now I could understand better. For my analysis, I first run the genome-wide iHS scan using the microarray data, then for those significant loci I attempted to use iSAFE to further dissect the signal and pinpoint favored variants based on an independent WGS dataset. Will it be good if I limit the input variants of iSAFE to those in LD with the lead iHS variant (e.g R2>= 0.7)? As I wanted to know which variant in the given haplotype is responsible for the selection. Could you give me suggestions for my analysis?

Best,
Xiaoxi
